// Verification Portal - Security Guard QR Verification Page
import { useState, useEffect } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import {
  Shield,
  CheckCircle,
  XCircle,
  Clock,
  Download,
  Printer,
  Car,
  User,
  FileText,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerDescription,
  DrawerFooter,
} from "@/components/ui/drawer";
import { useAuth } from "@/contexts/AuthContext";
import { gatePassApi } from "@/services/gate-pass-api";

interface VerificationData {
  gatePass: any;
  request: any;
  verification: any;
  code?: string;
  message?: string;
}

export const Route = createFileRoute("/verify/$token")({
  component: VerifyPage,
});

function VerifyPage() {
  const { token } = Route.useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [data, setData] = useState<VerificationData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [releasing, setReleasing] = useState(false);
  const [releaseDrawerOpen, setReleaseDrawerOpen] = useState(false);

  const [releaseForm, setReleaseForm] = useState({
    transportationType: "",
    vehiclePlate: "",
    driverName: "",
    kmReadingStart: "",
    remarks: "",
  });

  useEffect(() => {
    if (token) {
      validateToken(token);
    }
  }, [token]);

  const validateToken = async (verificationToken: string) => {
    try {
      setLoading(true);
      setError(null);
      const result = await gatePassApi.verifyQRToken(verificationToken);
      // fetchApi unwraps data.data, so result is the data object directly
      setData(result?.data || result);
    } catch (err: any) {
      const message = err?.message || "Invalid QR code";
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  const handleRelease = async () => {
    if (!token || !user) return;

    const requiresVehicle =
      releaseForm.transportationType === "Company Vehicle" ||
      releaseForm.transportationType === "Personal Vehicle";

    if (
      requiresVehicle &&
      (!releaseForm.vehiclePlate.trim() ||
        !releaseForm.driverName.trim())
    ) {
      toast.error("Vehicle plate number and driver name are required");
      return;
    }

    try {
      setReleasing(true);

      // Time Out is auto-generated by the backend server
      // We only send: plateNumber, driverName, kmReadingStart, remarks
      await gatePassApi.confirmQRVerification(token, {
        kmReadingStart: releaseForm.kmReadingStart ? Number(releaseForm.kmReadingStart) : undefined,
        plateNumber: releaseForm.vehiclePlate || undefined,
        driverName: releaseForm.driverName || undefined,
        remarks: releaseForm.remarks || "Released via security verification",
      });

      toast.success("Gate Pass released successfully");

      setReleaseDrawerOpen(false);

      // Re-validate to get updated status
      await validateToken(token);
    } catch (err: any) {
      toast.error(err?.message || "Failed to release gate pass");
    } finally {
      setReleasing(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    // TODO: Implement PDF download
    toast.info("PDF download coming soon");
  };

  const handleLogin = () => {
    navigate({ to: "/" });
  };

  // Check if user has permission to release
  const canRelease = user && (
    user.role?.toLowerCase() === "security" ||
    user.role?.toLowerCase() === "super_admin" ||
    user.role?.toLowerCase() === "admin"
  );

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <Shield className="w-16 h-16 animate-pulse text-blue-600 mx-auto mb-4" />
          <p className="text-lg font-medium">Validating QR Code...</p>
        </div>
      </div>
    );
  }

  // Check for lifecycle-specific codes from the backend
  const lifecycleCode = data?.code || data?.verification?.code;
  const isAlreadyCompleted = lifecycleCode === 'ALREADY_COMPLETED';
  const isExpired = lifecycleCode === 'EXPIRED';
  const isAlreadyReleased = lifecycleCode === 'ALREADY_RELEASED';

  if (error || !data || isAlreadyCompleted) {
    const titleMsg = isAlreadyCompleted 
      ? 'QR Code Already Used' 
      : isExpired 
        ? 'QR Code Expired' 
        : 'Verification Failed';
    const descMsg = isAlreadyCompleted
      ? 'This Gate Pass has already been completed and the QR code is permanently invalid.'
      : isExpired
        ? 'This QR Code has expired and is no longer valid for verification.'
        : (error || "Invalid QR code");
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
        <Card className="max-w-md w-full">
          <CardHeader>
            <CardTitle className={`flex items-center gap-2 ${isAlreadyCompleted || isExpired ? 'text-orange-600' : 'text-red-600'}`}>
              {isAlreadyCompleted || isExpired ? (
                <Clock className="w-6 h-6" />
              ) : (
                <XCircle className="w-6 h-6" />
              )}
              {titleMsg}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-gray-700 mb-4">{descMsg}</p>
            {data?.request?.controlNumber && (
              <p className="text-sm text-gray-500 mb-4 font-mono">
                Control Number: {data.request.controlNumber}
              </p>
            )}
            {!user && (
              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
                <p className="text-sm text-yellow-800">
                  Please log in to access the verification portal.
                </p>
              </div>
            )}
            <Button onClick={handleLogin} className="w-full">
              Go to Login
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const { gatePass, request, verification } = data;
  const isReleasedStatus = verification.status === "released";
  const isExpiredStatus = verification.status === "expired";

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-3xl font-bold text-gray-900 mb-2">
                HS TECHNOLOGIES (PHILS.), INC.
              </h1>
              <p className="text-lg font-semibold text-gray-700">Gate Pass Verification Portal</p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-600">Control Number</p>
              <p className="text-2xl font-mono font-bold text-red-600">{request.controlNumber}</p>
            </div>
          </div>
        </div>

        {/* Status Badge */}
        <div className="mb-6">
          <Badge
            variant={isReleasedStatus ? "default" : isExpiredStatus ? "destructive" : "secondary"}
            className="text-sm px-4 py-2"
          >
            {isReleasedStatus ? "Released" : isExpiredStatus ? "Expired" : "Ready for Verification"}
          </Badge>
        </div>

        {/* Gate Pass Details */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Gate Pass Details</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-sm font-medium text-gray-600">Employee</label>
                <p className="text-gray-900 font-medium">
                  {request.requester.employees?.firstName} {request.requester.employees?.lastName}
                </p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-600">Department</label>
                <p className="text-gray-900">{request.department?.name || "N/A"}</p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-600">Destination</label>
                <p className="text-gray-900">{gatePass.destination || "N/A"}</p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-600">Purpose</label>
                <p className="text-gray-900">{gatePass.purpose}</p>
              </div>
              {gatePass.vehicle && (
                <>
                  <div>
                    <label className="text-sm font-medium text-gray-600">Vehicle</label>
                    <p className="text-gray-900">
                      {gatePass.vehicle.brand} {gatePass.vehicle.model} ({gatePass.vehicle.plateNumber})
                    </p>
                  </div>
                  {gatePass.driverName && (
                    <div>
                      <label className="text-sm font-medium text-gray-600">Driver</label>
                      <p className="text-gray-900">{gatePass.driverName}</p>
                    </div>
                  )}
                </>
              )}
              <div>
                <label className="text-sm font-medium text-gray-600">Expected Return</label>
                <p className="text-gray-900">
                  {gatePass.expectedReturn ? new Date(gatePass.expectedReturn).toLocaleString() : "N/A"}
                </p>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-600">Scan Count</label>
                <p className="text-gray-900">{verification.scanCount || 0}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Approval Timeline */}
        <Card className="mb-6">
          <CardHeader>
            <CardTitle>Approval Timeline</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {request.steps?.map((step: any) => (
                <div key={step.id} className="flex items-start gap-3">
                  <div className="mt-1">
                    {step.status === "approved" ? (
                      <CheckCircle className="w-5 h-5 text-green-600" />
                    ) : step.status === "current" ? (
                      <Clock className="w-5 h-5 text-yellow-600" />
                    ) : (
                      <div className="w-5 h-5 rounded-full border-2 border-gray-300" />
                    )}
                  </div>
                  <div className="flex-1">
                    <p className="font-medium text-gray-900">{step.name}</p>
                    <p className="text-sm text-gray-600">
                      {step.actor?.displayName || "Pending"} • {step.role?.name}
                    </p>
                    {step.actedAt && (
                      <p className="text-xs text-gray-500">
                        {new Date(step.actedAt).toLocaleString()}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

{/* Actions */}
        {!isReleasedStatus && !isExpiredStatus && (
          <Card>
            <CardHeader>
              <CardTitle>Security Actions</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {canRelease ? (
                <>
                  <Button
                    onClick={() => {
                      setReleaseForm({
                        transportationType:
                          gatePass.transportationAssignment
                            ?.transportationType || "",
                        vehiclePlate:
                          gatePass.transportationAssignment?.vehiclePlate || "",
                        driverName:
                          gatePass.transportationAssignment?.driverName || "",
                        kmReadingStart: "",
                        remarks: "",
                      });

                      setReleaseDrawerOpen(true);
                    }}
                    disabled={releasing}
                    className="w-full bg-green-600 hover:bg-green-700"
                  >
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Release Employee
                  </Button>
                  <div className="flex gap-2">
                    <Button onClick={handlePrint} variant="outline" className="flex-1">
                      <Printer className="w-4 h-4 mr-2" />
                      Print
                    </Button>
                    <Button onClick={handleDownloadPDF} variant="outline" className="flex-1">
                      <Download className="w-4 h-4 mr-2" />
                      Download PDF
                    </Button>
                  </div>
                </>
              ) : (
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <p className="text-sm text-yellow-800">
                    {user
                      ? "You do not have permission to release gate passes. Please contact your administrator."
                      : "Please log in with your security credentials to release this gate pass."}
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        )}

{/* Released Info */}
        {isReleasedStatus && (
          <Card className="bg-green-50 border-green-200">
            <CardContent className="pt-6">
              <div className="flex items-start gap-3">
                <CheckCircle className="w-6 h-6 text-green-600 mt-1" />
                <div>
                  <p className="font-semibold text-green-900">Gate Pass Released</p>
                  <p className="text-sm text-green-700">
                    Released on {verification.releasedAt?.toLocaleString()}
                  </p>
                  {verification.remarks && (
                    <p className="text-sm text-green-700 mt-1">Remarks: {verification.remarks}</p>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        <Drawer
          open={releaseDrawerOpen}
          onOpenChange={setReleaseDrawerOpen}
        >
          <DrawerContent className="max-h-[95vh] overflow-y-auto">
            <DrawerHeader>
              <DrawerTitle className="text-2xl">
                Release Gate Pass
              </DrawerTitle>

              <DrawerDescription>
                This is the LAST STEP before releasing the employee.
              </DrawerDescription>
            </DrawerHeader>

            <div className="px-4 pb-6 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Employee Name
                  </p>
                  <p className="font-semibold">
                    {request.requester.employees?.firstName}{" "}
                    {request.requester.employees?.lastName}
                  </p>
                </div>

                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Control Number
                  </p>
                  <p className="font-semibold">
                    {request.controlNumber}
                  </p>
                </div>

                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Department
                  </p>
                  <p className="font-semibold">
                    {request.department?.name || "N/A"}
                  </p>
                </div>

                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Destination
                  </p>
                  <p className="font-semibold">
                    {gatePass.destination || "N/A"}
                  </p>
                </div>

                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Purpose
                  </p>
                  <p className="font-semibold">
                    {gatePass.purpose}
                  </p>
                </div>

                <div className="rounded-lg border p-4 bg-muted/20">
                  <p className="text-xs text-muted-foreground">
                    Expected Return
                  </p>
                  <p className="font-semibold">
                    {gatePass.expectedReturn
                      ? new Date(
                          gatePass.expectedReturn,
                        ).toLocaleString()
                      : "N/A"}
                  </p>
                </div>
              </div>

              <div className="rounded-xl border p-5 space-y-4">
                <div className="flex items-center gap-2">
                  <Car className="w-5 h-5 text-green-600" />
                  <h3 className="font-semibold text-lg">
                    Release Information
                  </h3>
                </div>

                <div>
                  <label className="text-sm font-medium mb-2 block">
                    Transportation Type
                  </label>

                  <select
                    value={releaseForm.transportationType}
                    onChange={(e) =>
                      setReleaseForm({
                        ...releaseForm,
                        transportationType: e.target.value,
                      })
                    }
                    className="w-full border rounded-lg px-3 py-2"
                  >
                    <option value="">Select transportation</option>
                    <option value="Company Vehicle">
                      Company Vehicle
                    </option>
                    <option value="Personal Vehicle">
                      Personal Vehicle
                    </option>
                    <option value="Commute">Commute</option>
                  </select>
                </div>

                {(releaseForm.transportationType ===
                  "Company Vehicle" ||
                  releaseForm.transportationType ===
                    "Personal Vehicle") && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="text-sm font-medium mb-2 block">
                        Vehicle Plate Number
                      </label>

                      <input
                        value={releaseForm.vehiclePlate}
                        onChange={(e) =>
                          setReleaseForm({
                            ...releaseForm,
                            vehiclePlate: e.target.value,
                          })
                        }
                        className="w-full border rounded-lg px-3 py-2"
                        placeholder="Enter plate number"
                      />
                    </div>

                    <div>
                      <label className="text-sm font-medium mb-2 block">
                        Driver Name
                      </label>

                      <input
                        value={releaseForm.driverName}
                        onChange={(e) =>
                          setReleaseForm({
                            ...releaseForm,
                            driverName: e.target.value,
                          })
                        }
                        className="w-full border rounded-lg px-3 py-2"
                        placeholder="Enter driver name"
                      />
                    </div>
                  </div>
                )}

                <div>
                  <label className="text-sm font-medium mb-2 block">
                    Security Remarks
                  </label>

                  <textarea
                    value={releaseForm.remarks}
                    onChange={(e) =>
                      setReleaseForm({
                        ...releaseForm,
                        remarks: e.target.value,
                      })
                    }
                    className="w-full border rounded-lg px-3 py-2 min-h-[100px]"
                    placeholder="Optional remarks"
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="rounded-lg border p-4 bg-green-50">
                    <div className="flex items-center gap-2 mb-1">
                      <User className="w-4 h-4 text-green-700" />
                      <p className="text-xs text-muted-foreground">
                        Released By
                      </p>
                    </div>

                    <p className="font-semibold">
                      {user?.email || "Security Guard"}
                    </p>
                  </div>

                  <div className="rounded-lg border p-4 bg-green-50">
                    <div className="flex items-center gap-2 mb-1">
                      <FileText className="w-4 h-4 text-green-700" />
                      <p className="text-xs text-muted-foreground">
                        Release Time
                      </p>
                    </div>

                    <p className="font-semibold">
                      {new Date().toLocaleString()}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <DrawerFooter>
              <div className="flex gap-3">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => setReleaseDrawerOpen(false)}
                >
                  Cancel
                </Button>

                <Button
                  onClick={handleRelease}
                  disabled={releasing}
                  className="flex-1 bg-green-600 hover:bg-green-700"
                >
                  <CheckCircle className="w-4 h-4 mr-2" />

                  {releasing
                    ? "Releasing Employee..."
                    : "Release Employee"}
                </Button>
              </div>
            </DrawerFooter>
          </DrawerContent>
        </Drawer>

        {/* Footer */}
        <div className="mt-8 text-center text-sm text-gray-500">
          <p>Electronically Generated by HST Enterprise Portal</p>
          <p>Verification Token: {token?.substring(0, 8)}...</p>
        </div>
      </div>
    </div>
  );
}