import type { RoleDefinition, RoleId } from "@/types";

// Ordered by authority level (1 = highest)
export const ROLES: Record<RoleId, RoleDefinition> = {
  super_admin: {
    id: "super_admin",
    name: "Super Administrator",
    shortName: "Super Admin",
    level: 1,
    purpose: "System Owner",
    description: "Full control of every module, user, role, workflow and system setting.",
    accentColor: "accent",
    demoUser: {
      name: "Daniel Cruz",
      email: "daniel.cruz@hst-corp.com",
      title: "System Owner",
      department: "Information Technology",
      avatarInitials: "DC",
    },
  },
  admin: {
    id: "admin",
    name: "System Administrator",
    shortName: "Administrator",
    level: 2,
    purpose: "ERP Administration",
    description: "Manages the ERP: employees, modules, users, departments and approvals.",
    accentColor: "primary",
    demoUser: {
      name: "Maria Santos",
      email: "maria.santos@hst-corp.com",
      title: "IT Administrator",
      department: "Information Technology",
      avatarInitials: "MS",
    },
  },
  executive: {
    id: "executive",
    name: "Executive",
    shortName: "Executive",
    level: 3,
    purpose: "Leadership Oversight",
    description: "Company dashboard, executive KPIs, analytics and approval monitoring. Read-only.",
    accentColor: "info",
    demoUser: {
      name: "Robert Tan",
      email: "robert.tan@hst-corp.com",
      title: "Plant General Manager",
      department: "Executive Office",
      avatarInitials: "RT",
    },
  },
  manager: {
    id: "manager",
    name: "Department Manager",
    shortName: "Manager",
    level: 4,
    purpose: "Department Leadership",
    description: "Department statistics, requests, approvals, employees and reports.",
    accentColor: "primary",
    demoUser: {
      name: "Grace Lim",
      email: "grace.lim@hst-corp.com",
      title: "Production Manager",
      department: "Production",
      avatarInitials: "GL",
    },
  },
  supervisor: {
    id: "supervisor",
    name: "Supervisor",
    shortName: "Supervisor",
    level: 5,
    purpose: "Team Supervision",
    description: "Approval queue, team requests, employee monitoring and recommendations.",
    accentColor: "info",
    demoUser: {
      name: "Jomar Reyes",
      email: "jomar.reyes@hst-corp.com",
      title: "Line Supervisor",
      department: "Production",
      avatarInitials: "JR",
    },
  },
  hr: {
    id: "hr",
    name: "HR Officer",
    shortName: "HR",
    level: 6,
    purpose: "People Operations",
    description: "Employee profiles, leave, visitors, records and HR reports.",
    accentColor: "accent",
    demoUser: {
      name: "Bianca Flores",
      email: "bianca.flores@hst-corp.com",
      title: "HR Officer",
      department: "Human Resources",
      avatarInitials: "BF",
    },
  },
  gad: {
    id: "gad",
    name: "General Administration",
    shortName: "GAD",
    level: 7,
    purpose: "Gate & Facilities",
    description: "Gate pass final approval, vehicle assignment, meal allowance and reports.",
    accentColor: "warning",
    demoUser: {
      name: "Andres Villa",
      email: "andres.villa@hst-corp.com",
      title: "GAD Officer",
      department: "General Administration",
      avatarInitials: "AV",
    },
  },
  security: {
    id: "security",
    name: "Security Guard",
    shortName: "Security",
    level: 8,
    purpose: "Gate Operations",
    description: "Today's gate pass, QR verification, vehicle in/out and visitor verification.",
    accentColor: "info",
    demoUser: {
      name: "Marco Diaz",
      email: "marco.diaz@hst-corp.com",
      title: "Security Officer",
      department: "Security",
      avatarInitials: "MD",
    },
  },
  employee: {
    id: "employee",
    name: "Employee",
    shortName: "Employee",
    level: 9,
    purpose: "Self Service",
    description: "Create and track own requests: gate pass, leave, MRF, purchase and more.",
    accentColor: "primary",
    demoUser: {
      name: "Liza Mendoza",
      email: "liza.mendoza@hst-corp.com",
      title: "Production Associate",
      department: "Production",
      avatarInitials: "LM",
    },
  },
};

// Hierarchy order for display
export const ROLE_ORDER: RoleId[] = [
  "super_admin",
  "admin",
  "executive",
  "manager",
  "supervisor",
  "hr",
  "gad",
  "security",
  "employee",
];

export const getRole = (id: RoleId): RoleDefinition => ROLES[id];
