import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import {
  FileText,
  Download,
  Printer,
  RefreshCw,
  Loader2,
  Eye,
} from "lucide-react";
import type { GatePass } from "@/services/gate-pass-api";
import type { WorkflowStatus } from "@/services/gate-pass-api";
import { getApiUrl } from "@/services/api-client";

interface DocumentViewerProps {
  gatePass: GatePass;
  workflowStatus: WorkflowStatus | null;
  isSuperAdmin: boolean;
  onRefresh: () => void;
}

export function DocumentViewer({
  gatePass,
  workflowStatus,
  isSuperAdmin,
  onRefresh,
}: DocumentViewerProps) {
  const [previewHtml, setPreviewHtml] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);

  useEffect(() => {
    loadPreview();
  }, [gatePass.requestId]);

  const loadPreview = async () => {
    try {
      setLoading(true);
      const response = await fetch(
        getApiUrl(`/gate-pass/${gatePass.requestId}/preview`)
      );
      if (response.ok) {
        const html = await response.text();
        setPreviewHtml(html);
      } else {
        throw new Error("Failed to load preview");
      }
    } catch (error) {
      console.error("Error loading preview:", error);
      toast.error("Failed to load document preview");
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(previewHtml);
      printWindow.document.close();
    }
  };

  const handleDownloadPdf = async () => {
    try {
      setGeneratingPdf(true);
      const response = await fetch(
        getApiUrl(`/gate-pass/${gatePass.requestId}/generate-pdf`),
        { method: "POST" }
      );
      
      if (response.ok) {
        const result = await response.json();
        
        // Download the PDF
        const downloadResponse = await fetch(
          getApiUrl(`/gate-pass/${gatePass.requestId}/download-pdf`)
        );
        
        if (downloadResponse.ok) {
          const blob = await downloadResponse.blob();
          const url = window.URL.createObjectURL(blob);
          const link = document.createElement("a");
          link.href = url;
          link.download = result.data.fileName;
          link.click();
          window.URL.revokeObjectURL(url);
          toast.success("PDF downloaded successfully");
        }
      } else {
        throw new Error("Failed to generate PDF");
      }
    } catch (error) {
      console.error("Error downloading PDF:", error);
      toast.error("Failed to download PDF");
    } finally {
      setGeneratingPdf(false);
    }
  };

  const handleRegeneratePdf = async () => {
    if (!isSuperAdmin) {
      toast.error("Only super admins can regenerate documents");
      return;
    }

    try {
      setGeneratingPdf(true);
      const response = await fetch(
        getApiUrl(`/gate-pass/${gatePass.requestId}/regenerate-pdf`),
        { method: "POST" }
      );
      
      if (response.ok) {
        toast.success("PDF regenerated successfully");
        onRefresh();
      } else {
        throw new Error("Failed to regenerate PDF");
      }
    } catch (error) {
      console.error("Error regenerating PDF:", error);
      toast.error("Failed to regenerate PDF");
    } finally {
      setGeneratingPdf(false);
    }
  };

  return (
    <div className="space-y-4">
      {/* Document Info */}
      <div className="bg-muted/30 rounded-lg p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="size-5 text-blue-600" />
            <div>
              <h3 className="font-semibold text-sm">Gate Pass Document</h3>
              <p className="text-xs text-muted-foreground">
                Control: {gatePass.controlNumber}
              </p>
            </div>
          </div>
          <span className="text-xs text-muted-foreground">
            Generated by System
          </span>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="px-2 py-1 bg-green-100 text-green-800 rounded-full font-medium">
            Ready
          </span>
          <span className="text-muted-foreground">
            Print Count: {gatePass.printCount || 0}
          </span>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="grid grid-cols-2 gap-2">
        <Button
          variant="default"
          size="sm"
          className="gap-2"
          onClick={loadPreview}
          disabled={loading}
        >
          {loading ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            <Eye className="size-4" />
          )}
          Preview
        </Button>

        <Button
          variant="outline"
          size="sm"
          className="gap-2"
          onClick={handlePrint}
          disabled={loading || !previewHtml}
        >
          <Printer className="size-4" />
          Print
        </Button>

        <Button
          variant="default"
          size="sm"
          className="gap-2"
          onClick={handleDownloadPdf}
          disabled={generatingPdf || loading}
        >
          {generatingPdf ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            <Download className="size-4" />
          )}
          Download PDF
        </Button>

        {isSuperAdmin && (
          <Button
            variant="secondary"
            size="sm"
            className="gap-2"
            onClick={handleRegeneratePdf}
            disabled={generatingPdf || loading}
          >
            {generatingPdf ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              <RefreshCw className="size-4" />
            )}
            Regenerate
          </Button>
        )}
      </div>

      {/* Preview iframe */}
      {previewHtml && (
        <div className="border-2 border-gray-200 rounded-lg overflow-hidden bg-white">
          <div className="bg-gray-50 px-4 py-2 border-b border-gray-200 flex items-center justify-between">
            <span className="text-xs font-medium text-gray-700">
              Document Preview
            </span>
            <span className="text-xs text-gray-500">
              WYSIWYG - What you see is what you get
            </span>
          </div>
          <iframe
            srcDoc={previewHtml}
            title="Document Preview"
            className="w-full h-[600px] border-0"
            sandbox="allow-scripts allow-modals"
          />
        </div>
      )}

      {!previewHtml && !loading && (
        <div className="text-center py-8 text-muted-foreground">
          <FileText className="w-12 h-12 mx-auto mb-2 opacity-50" />
          <p className="text-sm">Click Preview to load the document</p>
        </div>
      )}
    </div>
  );
}